### ISSUE TITLE
Installation via conda fails

### ISSUE THREAD

**Issue by ivanov-v-v** [limix/chi2comb-py#1]
Hello! First of all, I would like to thank you for the wonderful limix package. 
Unfortunately, I've encountered an installation issue. 
When I enter the "conda install -c conda-forge chi2comb" command, I get "PackagesNotFoundError" from conda. Could you, please, update the readme section for chi2comb package? Installing from source is not an option, because I don't have superuser access to this particular machine.
![image](https://user-images.githubusercontent.com/8493747/52978751-a330fc00-33e3-11e9-96f1-8f6886d49b59.png)

**Comment by horta** [comment]
Hi @ivanov-v-v , thanks a lot!. I've edited the README.md.
We still dont have an conda package for chi2comb, unfortunately. But you can install it via `pip install chi2comb`
