### ISSUE TITLE
How to be add more precision on p-value

### ISSUE THREAD

**Issue by FBoyang** [limix/chi2comb-py#3]
Dear developer:

I am using your method to perform multiple hypothesis tests. The test set is very big so I need to perform Bonferroni correction after getting all the p-values. However, most of the p-value I got using your algorithm are 0s. Therefore, I wonder if there is some way to increase the precision of the p-value so that I can pick the true signal after Bonferroni correction. Thank you!

Best 
Boyang

**Comment by horta** [comment]
I believe that has been fixed. It is now more precise.
