### ISSUE TITLE
installation issue in M1 MacMini

### ISSUE THREAD

**Issue by akhst7** [limix/chi2comb-py#7]
Hi, 

I am trying to install chi2comb in M1 Mac mini  running OSX 12.5, and running into a following build issues;

```
build/temp.macosx-12-arm64-cpython-310/chi2comb._ffi.c:569:10: fatal error: 'chi2comb.h' file not found
      #include "chi2comb.h"
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/opt/homebrew/opt/llvm/bin/clang' failed with exit code 1
```

Am I missing some prerequisite  libraries or some issues with an arm version of cpython ?

**Comment by jan-engelmann** [comment]
@akhst7 How did you solve this?
I get the same error on Apple M1 Pro
Python 3.8.13

I cannot install via conda or pip

**Comment by jan-engelmann** [comment]
The error I get is:
(Exactly the same as above)
```
      build/temp.macosx-11.0-arm64-cpython-38/chi2comb._ffi.c:569:10: fatal error: 'chi2comb.h' file not found
      #include "chi2comb.h"
               ^~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

Any idea on how to solve this @horta ?
Thanks a lot!

**Comment by jan-engelmann** [comment]
`brew install gcc` solved it for me!
